<?php

return [
	'menu' => [
		[
			'id' => 'menu-dashboard',
			'title' => 'Dashboard',
			'icon' => 'fa fa-dashboard',
			'href' => '/dashboard',
			'permissions' => ['view_report'],
			'children' => [],
		],
		[
			'id' => 'menu-account',
			'title' => 'Accounts',
			'icon' => 'fa fa-user',
			'href' => '',
			'permissions' => ['super_admin'],
			'children' => [
				[
					'id' => '',
					'title' => 'Users',
					'icon' => 'fa-building-o',
					'href' => 'admin/user',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Roles',
					'icon' => 'fa-building-o',
					'href' => 'admin/role',
					'permissions' => [],
					'children' => [],
				],
			],
		],
		[
			'id' => 'menu-manager',
			'title' => 'Menus',
			'icon' => 'fa fa-bars',
			'href' => '',
			'permissions' => ['menu_manage'],
			'children' => [
				[
					'id' => '',
					'title' => 'All Menu',
					'icon' => 'fa-building-o',
					'href' => 'admin/term/menugroup',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Menu structure',
					'icon' => 'fa-building-o',
					'href' => 'admin/menu',
					'permissions' => [],
					'children' => [],
				],

			],
		],
		[
			'id' => 'menu-config',
			'title' => 'Configs',
			'icon' => 'fa fa-cog',
			'href' => '',
			'permissions' => ['config_manage'],
			'children' => [
				[
					'id' => '',
					'title' => 'Website',
					'icon' => 'fa-building-o',
					'href' => 'admin/config-website',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Widget',
					'icon' => 'fa-building-o',
					'href' => 'admin/config-widget',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Icons',
					'icon' => 'fa-building-o',
					'href' => 'admin/config-icon',
					'permissions' => [],
					'children' => [],
				],

			],
		],
		[
			'id' => 'menu-resource',
			'title' => 'Resources',
			'icon' => 'fa fa-database',
			'href' => '',
			'permissions' => [],
			'children' => [
				[
					'id' => '',
					'title' => 'Album',
					'icon' => 'fa-building-o',
					'href' => 'admin/term/albumgroup',
					'permissions' => ['album_manage'],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Video',
					'icon' => 'fa-video-o',
					'href' => 'admin/term/videogroup',
					'permissions' => ['video_manage'],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Question',
					'icon' => 'fa-video-o',
					'href' => 'admin/term/questiongroup',
					'permissions' => ['question_manage'],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Customer Idea',
					'icon' => 'fa-video-o',
					'href' => 'admin/customeridea',
					'permissions' => ['customeridea_manage'],
					'children' => [],
				],
			],
		],
		[
			'id' => 'menu-post',
			'title' => 'Posts',
			'icon' => 'fa fa-newspaper-o',
			'href' => '',
			'permissions' => ['post_manage'],
			'children' => [
				[
					'id' => '',
					'title' => 'Categories',
					'icon' => 'fa-building-o',
					'href' => 'admin/term/category',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'All Post',
					'icon' => 'fa-building-o',
					'href' => 'admin/post',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Tags',
					'icon' => 'fa-building-o',
					'href' => 'admin/term/tag',
					'permissions' => [],
					'children' => [],
				],
				[
					'id' => '',
					'title' => 'Comments',
					'icon' => 'fa-building-o',
					'href' => 'admin/comment',
					'permissions' => [],
					'children' => [],
				],
			],
		],

		[
			'id' => 'menu-receive-data',
			'title' => 'Contacts',
			'icon' => 'fa fa-download',
			'href' => '/admin/receive',
			'permissions' => ['receive_manage'],
			'children' => [],
		],
	],
];